In [42]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [13]:
url = "https://survey.stackoverflow.co/2023/#technology-most-popular-technologies"

In [14]:
reponse = requests.get(url)

In [26]:
data = reponse.text
soup = BeautifulSoup(reponse.content, "html.parser")

In [27]:
list_table = soup.find_all("table")
len(list_table)

126

In [82]:
language = soup.find("table", {"id" : "language-prof5lolr"})
rows = language.find_all("tr")

Programming = pd.DataFrame(columns=["Index", "Language", "Percentage"])

for index, row in enumerate(rows):
    cols = row.find_all("td")
    name = cols[0].string
    id = index
    percent = cols[1].find_all("span")
    
    new_row = {"Index": id, "Language": name, "Percentage": percent[0].text}
    Programming = pd.concat([Programming, pd.DataFrame([new_row])], ignore_index=True)

Programming.drop("Index", axis = 1, inplace=True)
Programming

                   Language Percentage
0                JavaScript    65.82%
1                  HTML/CSS    52.83%
2                       SQL    51.52%
3                    Python    45.32%
4                TypeScript    43.75%
5   Bash/Shell (all shells)    32.74%
6                      Java    30.49%
7                        C#    29.16%
8                       C++    20.21%
9                       PHP    19.03%
10                        C    16.66%
11                       Go    14.32%
12               PowerShell    13.61%
13                     Rust    12.21%
14                   Kotlin      9.7%
15                     Ruby     6.94%
16                     Dart     6.13%
17                      Lua      5.2%
18                    Swift     4.96%
19                 Assembly     4.42%
20      Visual Basic (.Net)     3.92%
21                   Groovy     3.87%
22                   Delphi     3.23%
23                    Scala     3.21%
24                        R     3.17%
25                   MATLAB     2.98%
26                      VBA      2.9%
27                   Elixir     2.63%
28              Objective-C      2.6%
29                     Perl     2.34%
30                  Haskell      1.8%
31                 Solidity      1.4%
32                  Clojure     1.38%
33                     Lisp     1.33%
34                 GDScript     1.31%
35                   Erlang     1.09%
36                       F#     1.03%
37                    Julia     0.78%
38                   Prolog     0.76%
39                      Zig      0.7%
40                  Fortran     0.69%
41                      Ada     0.65%
42                     Apex     0.64%
43                    OCaml     0.63%
44                    Cobol     0.57%
45                  Crystal     0.42%
46                      SAS      0.4%
47                      Nim     0.32%
48                     Flow     0.25%
49                      APL     0.16%
50                     Raku     0.14%

In [83]:
database = soup.find("table", {"id":"database-learn4vrhw"})
rows1 = database.find_all("tr")

Databases = pd.DataFrame(columns=["Database", "Percentage"])

for row in rows1:
    cols = row.find_all("td")
    dtb = cols[0].string
    pct = cols[1].find("span").string
    new_row = {"Database": dtb, "Percentage":pct}
    Databases = pd.concat([Databases, pd.DataFrame([new_row])], ignore_index=True)
Databases

                      Database Percentage
0                        MySQL    45.71%
1                      MongoDB    28.15%
2                       SQLite    26.93%
3                   PostgreSQL    23.38%
4         Microsoft SQL Server    12.41%
5                      MariaDB    12.34%
6   Firebase Realtime Database     8.38%
7                       Oracle     6.88%
8              Cloud Firestore     6.75%
9             Microsoft Access     6.24%
10                       Redis     5.15%
11                    Supabase     3.15%
12                    BigQuery     2.36%
13               Elasticsearch     1.62%
14                          H2     1.55%
15                       Neo4J     1.42%
16                    Dynamodb     1.19%
17                   Cassandra     0.99%
18                    Firebird     0.96%
19                   Cosmos DB     0.84%
20                    InfluxDB     0.84%
21                 Cockroachdb     0.71%
22                     IBM DB2     0.61%
23                    Couch DB     0.58%
24                   Snowflake     0.53%
25                  Clickhouse     0.43%
26                     Datomic     0.43%
27                        Solr     0.43%
28                   Couchbase     0.36%
29                      DuckDB      0.3%
30                        TiDB     0.28%
31                     RavenDB     0.23%